# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Ashkan works/VHDL_project_2/phase2/phase2.cache/wt} [current_project]
set_property parent.project_path {D:/Ashkan works/VHDL_project_2/phase2/phase2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Ashkan works/VHDL_project_2/phase2/phase2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Wc.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Wf.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Wi.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Wo.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Uc.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Uf.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Ui.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Uo.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Bc.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Bf.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Bi.coe}}
add_files {{D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/Bo.coe}}
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wf_ROM/Wf_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wf_ROM/Wf_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wi_ROM/Wi_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wi_ROM/Wi_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wo_ROM/Wo_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wo_ROM/Wo_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uc_ROM/Uc_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uc_ROM/Uc_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uf_ROM/Uf_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uf_ROM/Uf_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Ui_ROM/Ui_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Ui_ROM/Ui_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uo_ROM/Uo_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Uo_ROM/Uo_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bc_ROM/Bc_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bc_ROM/Bc_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bf_ROM/Bf_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bf_ROM/Bf_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bi_ROM/Bi_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bi_ROM/Bi_ROM.dcp}}]
add_files -quiet {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bo_ROM/Bo_ROM.dcp}}
set_property used_in_implementation false [get_files {{d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Bo_ROM/Bo_ROM.dcp}}]
read_vhdl -vhdl2008 -library xil_defaultlib {
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/neurals_utils_pkg.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/multipier_module.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/add_module.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/tanh_module.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/sigmoid_module.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/matrix_multipler.vhd}
  {D:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/new/LSTM_cell.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top LSTM_cell -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef LSTM_cell.dcp

catch { report_utilization -file LSTM_cell_utilization_synth.rpt -pb LSTM_cell_utilization_synth.pb }
