# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM.xci
# IP: The module: 'Wc_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wc_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM.xci
# IP: The module: 'Wc_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ashkan works/VHDL_project_2/phase2/phase2.srcs/sources_1/ip/Wc_ROM/Wc_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wc_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
